### ISSUE TITLE
Cannot Run The Bot in Replit 

### ISSUE THREAD

**Issue by sunaxl13** [TFAGaming/DiscordJS-V14-Bot-Template#1]
I been receiving the same response I cannot run the bot and for some reason the bot went online while this response:

![Screenshot_20220811-101157](https://user-images.githubusercontent.com/97773166/184054466-43548278-29b4-401f-bc87-7f862c3b5676.png)

The Bot is Running but I keep saying this and a moment later it turned off
![Screenshot_20220811-102337](https://user-images.githubusercontent.com/97773166/184054589-e2e3dc5b-d0ae-4c96-90b3-6af2104798ad.png)

**Comment by TFAGaming** [comment]
For the first screenshot, the Run button should be `node index.js`, not `npm run start` because there is no script called `start` in package.json. I will make the guide more simplified.
For the second screenshot, I don't know. You probably didn't create a command called `help`.
