### ISSUE TITLE
I wants to use this command from v13

### ISSUE THREAD

**Issue by BxinoProductions** [TFAGaming/DiscordJS-V14-Bot-Template#10]
**I hade a bot on v13 but now im using ur handler template and i want to use this command how can i do it**

const { DiscordTogether } = require('discord-together');

module.exports = {
    name:'youtubetogether',
    aliases: ['youtube'],
    description:'Make Youtube Together',
    run: async (client, message, args,prefix) => {
      
    if(!message.member.permissions.has("USE_ACTIVITIES")) return message.channel.send(`You Musst Have USE ACTIVITIES permission.`)
        if(message.member.voice.channel) {
            client.discordTogether.createTogetherCode(message.member.voice.channel.id, 'youtube').then(async invite => {
              return message.channel.send(`Click on the link to start! ${invite.code}`);
            });
          } else {
            if (!message.member.voice.channel) {
                return message.reply('**Please Join Vc At First!**')
            }
          }
    }
}

**and also i wants change**

module.exports = {
    config: {
        name: "",
        description: "",
        usage: ""
    },

**to somthing like this**  

module.exports = {
    name:'youtubetogether',
    aliases: ['youtube'],
    description:'Make Youtube Together',
    run: async (client, message, args,prefix) => {

i main without config things if i cudent wcplain im in ur server BXINO#6217

**Comment by TFAGaming** [comment]
this is going to be a lot of edits...
Alright, go to prefix commands handler and change this:
```js
if (pull.config.name) {
        client.prefix_commands.set(pull.config.name, pull);
        console.log(`[HANDLER - PREFIX] Loaded a file: ${pull.config.name} (#${client.prefix_commands.size})`.brightGreen)
      } else {
        console.log(`[HANDLER - PREFIX] Couldn't load the file ${file}, missing module name value.`.red)
        continue;
      };
```
to this: (just remove `.config`)
```js
if (pull.name) {
        client.prefix_commands.set(pull.name, pull);
        console.log(`[HANDLER - PREFIX] Loaded a file: ${pull.name} (#${client.prefix_commands.size})`.brightGreen)
      } else {
        console.log(`[HANDLER - PREFIX] Couldn't load the file ${file}, missing module name value.`.red)
        continue;
      };
 ```
 
 Aliases still didn't add, but I will add them soon...
 
 Reply to my comment if it worked.
