### ISSUE TITLE
Modal Error.

### ISSUE THREAD

**Issue by AudiRoCWA** [TFAGaming/DiscordJS-V14-Bot-Template#11]
Eeverything works but when i click submit the modal gives error. Console is clear and everything works. how do i remove the error in modal
![image_2022-09-10_144806837](https://user-images.githubusercontent.com/92563008/189481911-9b75ecc0-947c-4b5b-9556-0a398211f493.png)

**Comment by TFAGaming** [comment]
If it responds in chat "Modals are working! Here is what have you typed: {...}", everything should work fine. But if it responds and shows an error, then I don't know. I will check the modals handler rn and test if it works or not.
