### ISSUE TITLE
Feature Request 

### ISSUE THREAD

**Issue by Neodevils** [TFAGaming/DiscordJS-V14-Bot-Template#14]
When time there will be button & select menu handlers?

**Comment by TFAGaming** [comment]
I'm currently working on a npm package, sorry :/ Probably soon.

**Comment by Neodevils** [comment]
> I'm currently working on a npm package, sorry :/ Probably soon.

Oh, okay!

**Comment by heliodoros** [comment]
For the buttons, this is what I added to interactionCreate.js right at the top inside client.on to facilitate a button that adds roles

```
if (interaction.isButton()) {
    if (interaction.customId === 'acceptrules') {
     var roletoadd = interaction.guild.roles.cache.find(role => role.name === "Member");
      if (interaction.member.roles.cache.has(roletoadd.id)) {
        return interaction.reply("Rules have already been accepted");
      }
      interaction.member.roles.add(roletoadd);
      return interaction.reply("You have accepted the rules, welcome!");
    }
```

**Comment by Neodevils** [comment]
> For the buttons, this is what I added to interactionCreate.js right at the top inside client.on to facilitate a button that adds roles
> 
> ```
> if (interaction.isButton()) {
>     if (interaction.customId === 'acceptrules') {
>      var roletoadd = interaction.guild.roles.cache.find(role => role.name === "Member");
>       if (interaction.member.roles.cache.has(roletoadd.id)) {
>         return interaction.reply("Rules have already been accepted");
>       }
>       interaction.member.roles.add(roletoadd);
>       return interaction.reply("You have accepted the rules, welcome!");
>     }
> ```

Oh thank you.
