### ISSUE TITLE
MongoDB problem: ReplicaSetNoPrimary

### ISSUE THREAD

**Issue by Matuzh** [TFAGaming/DiscordJS-V14-Bot-Template#15]
I forked a bot on repl.it and I didn't change anything, but config.js like it was said in guide. I don't understand why there's problem, because I searched it on internet and I've done what others said - I added my IP on whitelist and it's not working. Please, help me. 

![image](https://user-images.githubusercontent.com/98213749/192170632-a09a76c4-0527-45d3-8754-fb543ad3bcaf.png)

**Comment by TFAGaming** [comment]
do set your ip in your mongo uri

**Comment by TFAGaming** [comment]
not*

**Comment by Matuzh** [comment]
What do you mean? In a network access or in key?

**Comment by Matuzh** [comment]
Okay, I have solution. Thanks for help!
