### ISSUE TITLE
Show only text channels when using options for slash commands

### ISSUE THREAD

**Issue by Spacotic** [TFAGaming/DiscordJS-V14-Bot-Template#16]
I tried using
```js
channelTypes: ["GUILD_TEXT"],
```
but that didn't work and I would like to know how to make it so the user can only select text channels in this new versio

also is it still something like const thingy = interaction.options.getString('blahblahblah');
(found out it is but with numbers its getInteger)

**Comment by TFAGaming** [comment]
There is not an option for channel types, only possible way is putting this code:
```js
if (interaction.guild.channels.cache.get(interaction.options.get('CHANNEL_OPTION_NAME')).type !== 0) return interaction.reply("That is not a text channel!");
```
Channel types IDs are here: https://discord.com/developers/docs/resources/channel#channel-object-channel-types

**Comment by Spacotic** [comment]
ohhhh alright, they should add a feature for that anyways thanks!

**Comment by Spacotic** [comment]
wait i just found out that you can do
```js
channel_types: ["GUILD_TEXT"],
```
and it works
