### ISSUE TITLE
Unhandled Rejection: TypeError: Cannot read properties of undefined (reading: 'OWNERS')

### ISSUE THREAD

**Issue by LizyProject** [TFAGaming/DiscordJS-V14-Bot-Template#19]
I got a error just like this: 
![image](https://user-images.githubusercontent.com/91580494/201334510-6adbe7a2-00fd-481d-9091-2b7b0ca50de7.png)
Is this code error or i need to add something into the code?

**Comment by kyoyacchi** [comment]
Enter account's id in `config/config.js`

**Comment by TFAGaming** [comment]
I have fixed the error, and you should add your account ID to the array in OWNERS variable (config.js).
