### ISSUE TITLE
ID SyntaxError

### ISSUE THREAD

**Issue by louloubu08** [TFAGaming/DiscordJS-V14-Bot-Template#20]
I am not very talented for this but I copied my bot ID from discord and then put it in the config.js file and then this happens:
![B23C292B-AC86-4E05-A0BA-03DF65267F52](https://user-images.githubusercontent.com/118079843/201494357-a6ef5235-3c01-41d5-a02b-0c0f24087e11.jpeg)
How can I fix this ?
(I run the program on replit)

**Comment by DevinOfficial** [comment]
Show ur full code in `config.js`, it's probably just a typo or some wrong syntax

**Comment by louloubu08** [comment]
module.exports = {

  Prefix: "?", // YOUR BOT PREFIX.

  Users: {
    OWNERS: ["1005771454262030357", "601452978792300566"] // THE BOT OWNERS ID.
  },

  Handlers: {
    MONGO
  },

  Client: {
    TOKEN
    ID: "1040389563853586503"
  }

}

**Comment by louloubu08** [comment]
MONGO and TOKEN are hidden in the secret section of replit.

**Comment by TFAGaming** [comment]
Remove `MONGO` and `TOKEN` from config.js, so it should be like this:
```js
module.exports = {

Prefix: "?", // YOUR BOT PREFIX.

Users: {
   OWNERS: ["1005771454262030357", "601452978792300566"] // THE BOT OWNERS ID.
},

Handlers: {
},

Client: {
   ID: "1040389563853586503"
}

}
```
