### ISSUE TITLE
I start the bot up on repl.it,

### ISSUE THREAD

**Issue by ThirdBrickhead** [TFAGaming/DiscordJS-V14-Bot-Template#21]
But it only loads the modal and ping command, not the other ones.

**Comment by louloubu08** [comment]
Please look at this for more information:
https://github.com/TFAGaming/DiscordJS-V14-Bot-Template/wiki#registering-a-slash-command-into-discord

**Comment by TFAGaming** [comment]
https://github.com/TFAGaming/DiscordJS-V14-Bot-Template/issues/23
