### ISSUE TITLE
I start the bot on repl.it

### ISSUE THREAD

**Issue by ThirdBrickhead** [TFAGaming/DiscordJS-V14-Bot-Template#23]
But only ping and mymodal commands show up nothing else please explain this to me I already brought up this issue.

**Comment by louloubu08** [comment]
Please look at this for more information:
https://github.com/TFAGaming/DiscordJS-V14-Bot-Template/wiki#registering-a-slash-command-into-discord

**Comment by TFAGaming** [comment]
I still didn't understand. Well make sure that you have invited your bot with `application.commands` and `bot` scopes.
