### ISSUE TITLE
Problem with permissions

### ISSUE THREAD

**Issue by zkita** [TFAGaming/DiscordJS-V14-Bot-Template#26]
I place in `DEFAULT_MEMBERS_PERMISSION` the string **"Administrator"** but allow all users to execute the command.
Any way to solve it?

![webstorm64_VQX3bMFynu](https://user-images.githubusercontent.com/36092786/206087963-41388c91-be8f-4c82-b66a-780c1e15ffa5.png)

**Comment by TFAGaming** [comment]
Try to use `PermissionFlagsBits`, for an example: `PermissionFlagsBits.Administrator`.

I'm not sure about this solution, but if it worked, you can send a message here and close this issue.
