### ISSUE TITLE
Message and Prefix Command???

### ISSUE THREAD

**Issue by Elpistolero131** [TFAGaming/DiscordJS-V14-Bot-Template#27]
What is the difference between a message command and a prefix command or a user command?

**Comment by bogdanwebdeveloper** [comment]
see what command is in each and how you need to call it in chat. for prefix commands you use prefixCommand but I cant remember exactly for message commands. Next time I am able to look at the code I will update here.

**Comment by Elpistolero131** [comment]
ok thank's I'm waiting for your response about the message and user commands

**Comment by bogdanwebdeveloper** [comment]
As far as I understood from the code:
prefix commands: you use them with the prefix you set to do something
user commands: you need to click on the user and select the command you want to run from there (i believe you cant call this commands with text in chat)

**Comment by bogdanwebdeveloper** [comment]
![Screenshot_2022-12-26-20-55-48-724_com discord](https://user-images.githubusercontent.com/75477064/209576655-eeb97048-eeeb-44e3-8dac-4a8091fe38bf.jpg)
You can see the App tabs, then click on command.

**Comment by Elpistolero131** [comment]
I have not Avatar or user-info I have nothing

**Comment by bogdanwebdeveloper** [comment]
Does your bot work properly?

**Comment by Elpistolero131** [comment]
yes the prefix commands work

**Comment by bogdanwebdeveloper** [comment]
do you have the user commands in the folder?

**Comment by Elpistolero131** [comment]
yes

**Comment by bogdanwebdeveloper** [comment]
also make sure your bot has permissions

**Comment by Elpistolero131** [comment]
you have it?

**Comment by Elpistolero131** [comment]
when you test, have you 'Avatar' or other?

**Comment by bogdanwebdeveloper** [comment]
Invite the bot on the server with full permisions.
I really cant tell you why they dont work. Its your job to troubleshoot from here.

**Comment by bogdanwebdeveloper** [comment]
![Uploading Screenshot_2022-12-26-21-01-10-122_com.discord.jpg…]()

**Comment by Elpistolero131** [comment]
My bot have all of the permissions and his role is on the top

**Comment by bogdanwebdeveloper** [comment]
![Uploading Screenshot_2022-12-26-21-01-10-122_com.discord.jpg…]()

**Comment by Elpistolero131** [comment]
I don't see the screenshots

**Comment by bogdanwebdeveloper** [comment]
Me neither

**Comment by bogdanwebdeveloper** [comment]
When I click Apps, I have then User info and Avatar to select.

**Comment by Elpistolero131** [comment]
no nothing

**Comment by bogdanwebdeveloper** [comment]
I cant help you anymore. You need to debug.

**Comment by Elpistolero131** [comment]
oh @bogdanwebdeveloper it's good it works but it's not for user command it work for messages commands. So how user commands works?

**Comment by Elpistolero131** [comment]
it's good I undersdand how it work:

-**Prefix** Command: you need to use the prefix after the command, example: `!help`

-**User** Command: you need to right click on a user on the list of user on the right, go to `Apps` and choose the command.

-**Message** Command: you need to right click on a message, got to `Apps` and choose the command.
