### ISSUE TITLE
Bot Crashing

### ISSUE THREAD

**Issue by InseiderHD** [TFAGaming/DiscordJS-V14-Bot-Template#28]
Hello,

maybe you can help me.

<img width="650" alt="Screenshot" src="https://user-images.githubusercontent.com/76958201/211856546-075330af-2c86-40cb-8879-1a5976597b96.png">

**Comment by InseiderHD** [comment]
I just set it up, I did the readme nothing else

**Comment by TFAGaming** [comment]
Yes, just enable the intents. Here is a picture below: (Located in "bot" section in Discord developer portal)

![2023-01-15 20_48_03-Window](https://user-images.githubusercontent.com/92172698/212563689-dcc5884d-4c60-4972-83ab-700f7e3231cf.png)
