### ISSUE TITLE
Fix package.json

### ISSUE THREAD

**Issue by AnimaVillis** [TFAGaming/DiscordJS-V14-Bot-Template#32]
Hello,
For success install you need to fix little your package.
Here is full working package.json
`{
  "name": "discordjs-v14-bot-template",
  "version": "14.0.0",
  "description": "A Discord Bot template built by T.F.A#7524!",
  "main": "index.js",
  "scripts": {
    "start": "node index.js"
  },
  "keywords": [],
  "author": "T.F.A#7524",
  "license": "ISC",
  "dependencies": {
    "better-sqlite3": "^8.2.0",
    "colors": "^1.4.0",
    "discord-api-types": "^0.36.2",
    "discord.js": "^14.5.0",
    "mathjs": "^11.7.0",
    "moment": "^2.29.4",
    "mongoose": "^6.4.4",
    "ms": "^2.1.3",
    "node-fetch": "^2.6.7",
    "pretty-ms": "^6.0.1",
    "quick.db": "^9.0.5",
    "super-djs": "^1.7.4"
  }
}
`

**Comment by ZwaenepoelSander** [comment]
thanks!
