### ISSUE TITLE
Whenever i do node . it always gives me this error

### ISSUE THREAD

**Issue by Pino520** [TFAGaming/DiscordJS-V14-Bot-Template#33]
@PanIntegralus @AdamT20054 @TFAGaming 
![image](https://github.com/TFAGaming/DiscordJS-V14-Bot-Template/assets/134786336/ebcdb57b-2679-4531-b966-da73003ee108)

**Comment by TFAGaming** [comment]
Please reset your bot token NOW! If anybody sees your bot token, they have access to your bot and they could do anything!

The error is happening because why are you adding your bot token as a condition? If you want to, you must put it in a string type, which is kinda useless.

**Comment by Pino520** [comment]
So how do I fix it?

**Comment by Pino520** [comment]
@TFAGaming @PanIntegralus @AdamT20054

**Comment by TFAGaming** [comment]
Remove that line.

**Comment by Pino520** [comment]
The line with the token? @TFAGaming @PanIntegralus @AdamT20054

**Comment by Pino520** [comment]
@TFAGaming @PanIntegralus @AdamT20054

**Comment by TFAGaming** [comment]
Stop pinging us, this won't work. Just remove the line 35, like from the screenshot above.
