### ISSUE TITLE
err loading slash commands, in this last code update

### ISSUE THREAD

**Issue by KwaYLen** [TFAGaming/DiscordJS-V14-Bot-Template#54]

**Comment by TFAGaming** [comment]
I have tested it and there is no issue occurred while loading the application commands.
- You probably used an incorrect structure of one of the application commands you have created, please verify by checking the Discord API Docs: https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-structure
- Make sure that the bot token and the bot ID that you have used in the configuration file are correct, and come from one single bot (for example, you can't use a bot token with another different bot ID).
