### ISSUE TITLE
Unable to load application commands

### ISSUE THREAD

**Issue by MRxMAG1C** [TFAGaming/DiscordJS-V14-Bot-Template#63]
When i run `node .`
it gives me this error before starting the bot: 
`[ERROR] Unable to load application commands to Discord API: Cannot read properties of undefined (reading 'guild')`

I haven't used 2 diffrent bots for token and id and havn't touched the slash commands, so im a bit lost here.

What code can i send to help solve this?

**Comment by TFAGaming** [comment]
This property is missing in your config.js file:
```ts
development: { 
    enabled: true,
    guild: "Enter your guild ID" // <-- This one
}, 
```

**Comment by MRxMAG1C** [comment]
Thank you!
