### ISSUE TITLE
test.js not working?

### ISSUE THREAD

**Issue by kanetjuh** [TFAGaming/DiscordJS-V14-Bot-Template#7]
A function in the code seems to not work? This is the user command/app called `./commands/message/test` (See images)

![image](https://user-images.githubusercontent.com/50002439/188905491-57003048-3789-4c85-8853-2f13564d883d.png)
![image](https://user-images.githubusercontent.com/50002439/188905532-9ee409b1-387a-461e-8c8d-6dec1fabcca4.png)

**Comment by kanetjuh** [comment]
Message command.

**Comment by TFAGaming** [comment]
Weird, I tested the same command on VSCode and it's working. Probably you did an error.

**Comment by kanetjuh** [comment]
Impossible? I just forked it. I only editted owners.js and that's all.

**Comment by TFAGaming** [comment]
Did you put your client ID in config.js?
And here is a ss that it's working for me (Message command)
![2022-09-07 16_12_37-Window](https://user-images.githubusercontent.com/92172698/188914499-19ca6229-f461-44f1-9ed2-1193a06fc557.png)

**Comment by kanetjuh** [comment]
Yes I did. Here a video of me trying to do it.

![Code_tm5uMMUWkU](https://user-images.githubusercontent.com/50002439/188915382-335e098a-a292-4072-9cb3-15ee1b1ae06c.gif)

**Comment by TFAGaming** [comment]
Does in the file `interactionCreate.js` in the folder `events` contains this code?
```js
if (interaction.isMessageContextMenuCommand()) { // Message:
    const command = client.message_commands.get(interaction.commandName);

    if (!command) return;

    try {
      command.run(client, interaction, config, db);
    } catch (e) {
      console.error(e)
    };
  };
```
Because that's super weird that it doesn't work for you, and works for me. Im going to recheck everything...
